'use strict';
const $=s=>document.querySelector(s),KEY='palaestina-adventure-v1';
const fresh=()=>({version:1,solved:Array(5).fill(false),answers:Array.from({length:5},()=>({})),attempts:Array(5).fill(0)});
let state=fresh(),active=0,pending=null,opener=null;
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved?.version===1&&Array.isArray(saved.solved)&&saved.solved.length===5&&saved.answers?.length===5&&saved.attempts?.length===5)state=saved;}catch{ }
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{$('#storage-note').textContent='Der Browser kann den Fortschritt nicht speichern. Die App funktioniert für diese Sitzung weiter.';}}
function esc(t){return String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function options(key,items){return `<div class="options">${items.map((t,i)=>`<button class="option ${state.answers[active][key]===i?'selected':''}" data-key="${key}" data-value="${i}" aria-pressed="${state.answers[active][key]===i}">${esc(t)}</button>`).join('')}</div>`;}
function scene(){const count=state.solved.filter(Boolean).length;$('#hotspots').innerHTML=PUZZLES.map((p,i)=>`<button class="hotspot ${state.solved[i]?'done':''}" style="left:${p.pos[0]}%;top:${p.pos[1]}%" data-open="${i}" aria-label="${p.object}: ${state.solved[i]?'gelöst':'ungelöst'}"><span class="tag-seal" aria-hidden="true"><img src="seal-${state.solved[i]?'open':'closed'}.webp" alt="">${state.solved[i]?'':`<span>${i+1}</span>`}</span><span class="tag-label">${p.object}</span></button>`).join('');$('#seals').innerHTML=state.solved.map((v,i)=>`<img class="seal" src="seal-${v?'open':'closed'}.webp" alt="Siegel ${i+1}: ${v?'offen':'geschlossen'}">`).join('');$('#progress').textContent=count===5?'Alle fünf Siegel sind geöffnet.':`${count} von 5 Siegeln geöffnet` ;$('#backdrop').src=`control-post${count===5?'-open':''}.webp`;$('#end').hidden=count!==5;requestAnimationFrame(positionMarkers);}
function open(i){active=i;pending=null;opener=document.activeElement;$('#chapter').textContent=`SIEGEL ${i+1} · ${PUZZLES[i].object}`;$('#title').textContent=PUZZLES[i].name;$('#knowledge-text').innerHTML=PUZZLES[i].knowledge.map(k=>`<p><strong>${KNOWLEDGE[k][0]}.</strong> ${KNOWLEDGE[k][1]}</p>`).join('');$('#knowledge').open=false;$('#feedback').textContent='';render();$('#puzzle').showModal();$('#puzzle .scroll').scrollTop=0;}
function render(){const a=state.answers[active];let html='';
if(active===0){const pairs=a.pairs||{};html='<p>Tippt zuerst eine Herrschaftsform links und dann ihre Folge rechts an. Verbindungen lassen sich durch erneutes Antippen ändern.</p><div class="columns"><div class="stack">'+LEFT.map((t,i)=>`<button class="card ${pending===i?'selected':''} ${pairs[i]!==undefined?'connected':''}" data-left="${i}">${i+1}. ${t}${pairs[i]!==undefined?`<br><small>→ ${RIGHT[pairs[i]]}</small>`:''}</button>`).join('')+'</div><div class="stack">'+[3,0,4,2,1].map(i=>`<button class="card" data-right="${i}">${RIGHT[i]}</button>`).join('')+'</div></div><h3>Vom Eingriff zur Erfahrung</h3><p>Bildet anschließend drei Ursache-Folge-Ketten. Wählt pro Kette einen Zwischenschritt und eine Folge.</p>'+CHAINS.map((c,i)=>`<div class="row"><h4>${c.start} →</h4>${options('mid'+i,c.mid)}<strong>→ Welche Erfahrung folgt daraus?</strong>${options('end'+i,c.end)}</div>`).join('');}
if(active===1){const marked=a.marked||[];html='<p>In der Akte sind genau drei Aussagen falsch. Markiert sie und wählt für jede eine fachlich passende Korrektur.</p>'+STATEMENTS.map((t,i)=>`<div class="row"><button class="card ${marked.includes(i)?'selected':''}" data-mark="${i}" aria-pressed="${marked.includes(i)}">${i+1}. ${t}</button>${marked.includes(i)?options('correct'+i,CORRECTIONS[i]?.options||['Diese Aussage soll unverändert in der Akte stehen.','Die Aussage umkehren.','Die Aussage streichen.']):''}</div>`).join('');}
if(active===2)html='<p>Ordnet jeder Stimme eine Haltung und eine passende Begründung zu.</p>'+PEOPLE.map((p,i)=>`<div class="row"><h4>${p[0]}</h4><p>„${p[1]}“</p><strong>Haltung</strong>${options('att'+i,ATTITUDES)}<strong>Begründung</strong>${options('reason'+i,REASONS)}</div>`).join('')+'<div class="row"><h4>Welche Aussage beschreibt die Situation am besten?</h4>'+options('overall',['Die jüdische Bevölkerung reagierte einheitlich.','Die Menschen reagierten unterschiedlich auf die Herrschaft.','Fast alle wollten gewaltsamen Widerstand.','Fast alle akzeptierten Rom.'])+'</div>';
if(active===3){const step=a.step||0;html='<p>Findet zu jedem Hinweis den passenden Ort, das Gewässer oder die Region. Alle neun Namen sind auf der Karte anwählbar.</p><div class="map-layout"><div class="map"><img src="palestine-map.webp" alt="Handgezeichnete Karte: Galiläa im Norden, Samaria in der Mitte, Judäa im Süden; Jordan zwischen See Genezareth und Totem Meer.">'+PLACES.map((p,i)=>`<button data-place="${i}" style="left:${p[1]}%;top:${p[2]}%" class="${a.place===i?'selected':''}">${p[0]}</button>`).join('')+'</div><div>';if(step<6)html+=`<div class="clue"><span class="eyebrow">HINWEIS ${step+1} VON 6</span><h4>${CLUES[step][0]}</h4><p>${a.place!==undefined?'Gewählt: '+PLACES[a.place][0]:'Tippt auf einen Namen auf der Karte.'}</p></div>`;else html+='<h4>Alle sechs Orte gefunden. Denkt weiter:</h4><p>Warum war Galiläa für die weitere Einheit besonders wichtig?</p>'+options('transfer0',['Weil dort der Tempel stand.','Weil Jesus dort lebte und wirkte.','Weil Rom dort gegründet wurde.'])+'<p>Warum war Jerusalem für Juden besonders wichtig?</p>'+options('transfer1',['Dort stand der Tempel.','Dort lag der See Genezareth.','Dort wurde der Kaiser gewählt.']);html+='</div></div>';}
if(active===4){const marked=a.marked||[];html='<p><strong>1.</strong> Markiert vier relevante Textstellen. Die einleitende Ortsangabe allein ist noch kein Beleg für eine Belastung.</p><div>'+REPORT.map((t,i)=>`<button class="passage ${marked.includes(i)?'selected':''}" data-mark="${i}" aria-pressed="${marked.includes(i)}">${t}</button>`).join('')+'</div><p><strong>2.</strong> Ordnet den markierten Stellen jeweils einen Schwerpunkt zu. Beim Kaiserbild geht es hier um die sichtbare politische Macht; die Straßensperre gehört zu Alltag/Kontrolle.</p>'+marked.map(i=>`<div class="row"><p>${REPORT[i]}</p>${options('category'+i,CATEGORIES)}</div>`).join('')+'<p><strong>3.</strong> Formuliert einen Satz, der erklärt, warum die römische Herrschaft für viele Menschen belastend war.</p><label for="sentence">Euer Erklärungssatz (mindestens 40 Zeichen)</label><textarea id="sentence" placeholder="Die römische Herrschaft …">'+esc(a.sentence||'')+'</textarea><p><small>Der Satz wird nur auf Mindestlänge geprüft. Vergleicht euren Gedanken anschließend mit der Musterlösung.</small></p>'+(state.solved[4]?`<details><summary>Musterlösung ansehen</summary><p>${MODEL}</p></details>`:'');}
const art=['objects/edict-board','objects/coin-table','characters/group-people','objects/map-table','objects/report-scroll'][active];
$('#task').innerHTML=`<div class="task-art"><img src="${art.split("/").pop()}.webp" alt="${PUZZLES[active].object}">${active===2?'<img src="roman-guard.webp" alt="Ein römischer Soldat">':''}</div>`+html;$('#solved').textContent=state.solved[active]?'Siegel geöffnet · weiterhin bearbeitbar':'';$('#check').textContent=active===3&&(a.step||0)<6?'Ort prüfen':'Lösung prüfen';}
function failure(message='Das passt noch nicht vollständig. Überprüft eure Zuordnungen und nutzt bei Bedarf „Wissen nachlesen“.'){state.attempts[active]++;save();$('#feedback').textContent=message+(state.attempts[active]>=2?' Hinweis: '+PUZZLES[active].hint:'');}
function check(){const a=state.answers[active];let ok=false;
if(active===0)ok=LEFT.every((_,i)=>a.pairs?.[i]===i)&&CHAINS.every((c,i)=>a['mid'+i]===c.answer[0]&&a['end'+i]===c.answer[1]);
if(active===1)ok=a.marked?.length===3&&[0,3,5].every(i=>a.marked.includes(i)&&a['correct'+i]===CORRECTIONS[i].answer);
if(active===2)ok=PEOPLE.every((p,i)=>a['att'+i]===p[2]&&a['reason'+i]===p[3])&&a.overall===1;
if(active===3){const step=a.step||0;if(step<6){if(a.place===CLUES[step][1]){a.step=step+1;delete a.place;save();render();$('#feedback').textContent=step===5?'Sechs Treffer! Beantwortet jetzt die beiden Transferfragen.':'Dieser Ort passt. Weiter zum nächsten Hinweis.';}else failure('Dieser Ort passt noch nicht zum Hinweis.');return;}ok=a.transfer0===1&&a.transfer1===0;}
if(active===4)ok=a.marked?.length===4&&[1,2,3,4].every(i=>a.marked.includes(i))&&a.category1===2&&a.category2===0&&a.category3===1&&a.category4===3&&(a.sentence||'').trim().length>=40;
if(!ok){failure();return;}const newly=!state.solved[active];state.solved[active]=true;save();scene();render();$('#feedback').textContent='Das passt. Ihr habt dieses Siegel geöffnet.';if(newly&&state.solved.every(Boolean)){ $('#puzzle').close();$('#finale').showModal();}}
$('#task').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=state.answers[active];if(b.dataset.key){a[b.dataset.key]=Number(b.dataset.value);}else if(b.dataset.left!==undefined){pending=Number(b.dataset.left);}else if(b.dataset.right!==undefined){if(pending===null){$('#feedback').textContent='Wählt zuerst eine Herrschaftsform links.';return;}a.pairs||={};const right=Number(b.dataset.right);for(const k in a.pairs)if(a.pairs[k]===right)delete a.pairs[k];a.pairs[pending]=right;pending=null;}else if(b.dataset.mark!==undefined){const i=Number(b.dataset.mark);a.marked||=[];a.marked=a.marked.includes(i)?a.marked.filter(x=>x!==i):[...a.marked,i].sort();}else if(b.dataset.place!==undefined){a.place=Number(b.dataset.place);}const scroll=$('#puzzle .scroll').scrollTop;save();render();$('#puzzle .scroll').scrollTop=scroll;const selector=b.dataset.key?`[data-key="${b.dataset.key}"][data-value="${b.dataset.value}"]`:b.dataset.left!==undefined?`[data-left="${b.dataset.left}"]`:b.dataset.right!==undefined?`[data-right="${b.dataset.right}"]`:b.dataset.mark!==undefined?`[data-mark="${b.dataset.mark}"]`:`[data-place="${b.dataset.place}"]`;$('#task').querySelector(selector)?.focus({preventScroll:true});});
$('#task').addEventListener('input',e=>{if(e.target.id==='sentence'){state.answers[4].sentence=e.target.value;save();}});
$('#puzzle').setAttribute('aria-labelledby','title');$('#finale').setAttribute('aria-label','Der Weg ist frei');$('#reset-dialog').setAttribute('aria-label','Fortschritt zurücksetzen');
$('#hotspots').addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)open(Number(b.dataset.open));});$('#check').onclick=check;$('#close').onclick=()=>$('#puzzle').close();$('#puzzle').addEventListener('close',()=>opener?.focus());$('#end').onclick=()=>{if(state.solved.every(Boolean))$('#finale').showModal();};$('#return').onclick=()=>$('#finale').close();$('#reset').onclick=()=>$('#reset-dialog').showModal();$('#cancel-reset').onclick=()=>$('#reset-dialog').close();$('#confirm-reset').onclick=()=>{state=fresh();save();scene();$('#reset-dialog').close();};scene();

function positionMarkers(){
 const layer=$('#object-markers'),image=$('#backdrop');if(!layer||!image.naturalWidth)return;
 const base=layer.getBoundingClientRect(),r=image.getBoundingClientRect();
 const scale=Math.min(r.width/image.naturalWidth,r.height/image.naturalHeight);
 const width=image.naturalWidth*scale,height=image.naturalHeight*scale;
 const offsetX=r.left-base.left+(r.width-width)/2,offsetY=r.top-base.top+(r.height-height)/2;
 layer.replaceChildren();
 PUZZLES.forEach((p,i)=>{
  const label=$(`[data-open="${i}"]`).getBoundingClientRect();
  const targetX=offsetX+width*p.anchor[0]/100,targetY=offsetY+height*p.anchor[1]/100;
  const x=Math.max(label.left+8,Math.min(base.left+targetX,label.right-8))-base.left;
  const y=(base.top+targetY>=label.bottom?label.bottom:label.top)-base.top;
  const dx=targetX-x,dy=targetY-y;
  const line=document.createElement('span');line.className='object-line';
  line.style.cssText=`left:${x}px;top:${y}px;width:${Math.hypot(dx,dy)}px;transform:rotate(${Math.atan2(dy,dx)}rad)`;
  const dot=document.createElement('span');dot.className='object-point';dot.dataset.object=i;
  dot.style.cssText=`left:${targetX}px;top:${targetY}px`;
  layer.append(line,dot);
 });
}
const markerLayer=document.createElement('div');markerLayer.id='object-markers';markerLayer.setAttribute('aria-hidden','true');$('#scene').insertBefore(markerLayer,$('#hotspots'));
new ResizeObserver(positionMarkers).observe($('#scene'));
$('#backdrop').addEventListener('load',positionMarkers);
$('#hotspots').addEventListener('pointerover',e=>{const b=e.target.closest('[data-open]');if(b)markerLayer.querySelector(`[data-object="${b.dataset.open}"]`)?.classList.add('lit');});
$('#hotspots').addEventListener('pointerout',()=>markerLayer.querySelectorAll('.lit').forEach(e=>e.classList.remove('lit')));
requestAnimationFrame(positionMarkers);
