const KNOWLEDGE=[
['Herrschaft','Palästina stand unter römischer Herrschaft. Rom setzte Herrscher und Beamte ein, die römische Interessen durchsetzten. In Galiläa regierte Herodes Antipas, solange Rom ihm vertraute. In Judäa setzte Rom eigene Statthalter ein. Die Bevölkerung konnte daher nicht selbst bestimmen, wer über sie herrschte. Römische Soldaten bewachten wichtige Orte, kontrollierten Straßen und gingen gegen Widerstand vor.'],
['Belastungen','Die Menschen mussten Steuern und andere Abgaben zahlen. Für wohlhabende Familien war das oft leichter zu tragen als für arme Bauern und Handwerker. Nach schlechten Ernten konnte die Belastung so groß werden, dass kaum genug zum Leben blieb. Zeichen römischer Herrschaft waren auch im Alltag sichtbar, zum Beispiel auf Münzen.'],
['Religion','Juden glaubten an den einen Gott. Die Römer verehrten dagegen viele Götter; auch der Kaiser wurde besonders verehrt. Viele Juden lehnten diese Verehrung ab und wollten ihren Glauben und ihre Traditionen bewahren. Dadurch entstanden religiöse Spannungen.'],
['Reaktionen','Die Menschen reagierten unterschiedlich auf die römische Herrschaft. Manche arrangierten sich und versuchten, ihren Alltag weiterzuleben. Andere hofften auf Freiheit. Manche wollten die Römer mit Gewalt vertreiben. Solche Widerstandskämpfer werden häufig als Zeloten bezeichnet.'],
['Palästina','Palästina gliederte sich in Galiläa im Norden, Samaria in der Mitte und Judäa im Süden. Der Jordan fließt durch das Land. Der See Genezareth liegt in Galiläa. Kafarnaum lag am Nordufer des Sees. Jerusalem war die wichtigste Stadt Judäas und Standort des Tempels.']];
const PUZZLES=[
{name:'Herrschaftsnetz',object:'Erlassbrett',pos:[15,42],knowledge:[0,1,2],hint:'Unterscheidet politische, wirtschaftliche und religiöse Folgen. Eine Kette führt von einer Maßnahme über ihre Wirkung zum Erleben der Menschen.'},
{name:'Manipulierte Akte',object:'Abgabentisch',pos:[30,73],knowledge:[0,1,2],hint:'Prüft besonders, wer Herrscher bestimmte, wo Rom im Alltag sichtbar war und wie viele Juden zur Kaiserverehrung standen.'},
{name:'Stimmen unter Besatzung',object:'Figurengruppe',pos:[77,46],knowledge:[0,1,3],hint:'Achtet auf die Verben: weiterleben, hoffen, kämpfen und sichern. Haltung und Begründung müssen zur selben Stimme passen.'},
{name:'Karte Palästinas',object:'Karte',pos:[78,77],knowledge:[4],hint:'Orientiert euch zuerst an Norden, Mitte und Süden. Unterscheidet dann Orte, Gewässer und Regionen.'},
{name:'Zacharias’ Bericht',object:'Pergamentrolle',pos:[54,82],knowledge:[0,1,3],hint:'Sucht die vier konkreten Erfahrungen: Kontrolle, ein sichtbares Zeichen der kaiserlichen Macht, Abgaben und Hoffnung auf Selbstbestimmung.'}];
const LEFT=['Rom setzte Herrscher und Beamte ein.','Soldaten kontrollierten Straßen und wichtige Orte.','Steuern und Abgaben wurden verlangt.','Römische Götter und Kaiserverehrung waren präsent.','Kaiserbilder waren auf Münzen sichtbar.'];
const RIGHT=['politische Fremdbestimmung','Kontrolle, Angst und ständige Machterfahrung','wirtschaftliche Belastung besonders armer Familien','religiöse Spannungen','römische Herrschaft wird im Alltag sichtbar'];
const CHAINS=[{start:'Rom setzt Herrscher ein',mid:['Menschen bestimmen nicht selbst','Menschen zahlen keine Abgaben','Menschen verehren viele Götter'],end:['Gefühl von Unfreiheit','Mehr Geld für arme Familien','Religiöse Einigkeit'],answer:[0,0]}, {start:'Abgaben werden auch nach schlechter Ernte verlangt',mid:['Bauern können frei über Herrscher entscheiden','Armen Familien bleibt wenig zum Leben','Soldaten verlassen das Land'],end:['Wirtschaftliche Sicherheit für alle','Ende der Fremdherrschaft','Existenzsorgen nehmen zu'],answer:[1,2]}, {start:'Kaiserverehrung wird öffentlich sichtbar',mid:['Viele Juden wollen ihren Glauben an den einen Gott bewahren','Alle Juden übernehmen römische Religion','Der Tempel verliert für alle seine Bedeutung'],end:['Alle reagieren gleich','Religiöse Spannungen entstehen','Abgaben werden abgeschafft'],answer:[0,1]}];
const STATEMENTS=['Die Menschen in Galiläa konnten selbst bestimmen, wer über sie herrschte.','Herodes Antipas durfte herrschen, solange Rom ihm vertraute.','Soldaten kontrollierten wichtige Orte und Straßen.','Die römische Herrschaft spielte im Alltag kaum eine Rolle.','Hohe Abgaben trafen besonders arme Familien hart.','Viele Juden übernahmen die Kaiserverehrung bereitwillig.'];
const CORRECTIONS={0:{options:['Rom entschied, welche Herrscher es unterstützte.','Die Bauern wählten Herodes Antipas.','Galiläa hatte keine Herrscher.'],answer:0},3:{options:['Rom war nur bei Festen sichtbar.','Münzen, Abgaben und Kontrollen machten Rom im Alltag spürbar.','Nur reiche Menschen begegneten römischer Macht.'],answer:1},5:{options:['Jüdische Religion war vollständig verboten.','Alle Juden kämpften gegen Rom.','Viele Juden lehnten Kaiserverehrung ab und bewahrten ihren Glauben.'],answer:2}};
const PEOPLE=[['Miriam, Händlerin','Ich kann Rom nicht ändern. Ich versuche weiterzuleben.',0,2],['Jakob, Bauer','Ich hoffe, dass wir eines Tages wieder selbst bestimmen.',1,3],['Eleasar','Nur wenn wir kämpfen, verschwinden die Römer.',2,0],['Marcus, Soldat','Wir sichern die römische Ordnung.',3,1]];
const ATTITUDES=['arrangiert sich','hofft auf Freiheit','gewaltsamer Widerstand','römische Ordnungsmacht'];
const REASONS=['Ablehnung der Fremdherrschaft mit dem Ziel, Rom kämpfend zu vertreiben','Kontrolle im Auftrag Roms','Alltag trotz Besatzung fortführen','Wunsch nach Selbstbestimmung angesichts von Fremdbestimmung und Belastung'];
const PLACES=[['Galiläa',34,13],['Samaria',30,47],['Judäa',29,86],['Jordan',70,48],['See Genezareth',76,27],['Jerusalem',44,65],['Kafarnaum',66,17],['Nazareth',40,32],['Bethlehem',43,76]];
const CLUES=[['Region im Norden, in der der See Genezareth liegt',0],['Region zwischen Galiläa und Judäa',1],['Stadt in Judäa mit dem Tempel',5],['Fischerdorf am Nordufer des Sees Genezareth',6],['Ort in Galiläa, mit dem Jesus besonders verbunden wird',7],['Fluss, der durch Palästina fließt und in das Tote Meer mündet',3]];
const REPORT=['Auf dem Heimweg kommen Zacharias und Joschua an einer Straßensperre vorbei.','Römische Soldaten kontrollieren die Reisenden und ihre Waren.','Auf dem Markt bezahlt ein Händler mit einer Münze, auf der das Bild des Kaisers zu sehen ist. Zacharias erinnert sich daran, dass selbst beim Einkaufen die Macht Roms sichtbar bleibt.','Später erzählt sein Vater, dass die Ernte schlecht war. Trotzdem müssen Steuern und Abgaben bezahlt werden.','Beim Abendessen sagt sein älterer Bruder leise: „Ich hoffe, dass wir eines Tages wieder selbst über unser Land bestimmen können.“'];
const CATEGORIES=['POLITISCH','WIRTSCHAFTLICH','ALLTAG/KONTROLLE','HOFFNUNG/REAKTION'];
const MODEL='Die römische Herrschaft beeinflusste Politik, Wirtschaft und Alltag, weshalb sich viele Menschen unfrei und belastet fühlten und auf Veränderung hofften.';
